#!/usr/local/bin/python
# -*- coding: utf-8 -*-

text_1 = 'Could not change owner of the script. Currently set user in config file is wrong!'
text_2 = 'You have to be logged as privileged user!'
text_3 = 'Change variable in config file named "owner_of_the_script"'
text_4 = 'No error found'
text_5 = 'NONE LOG FILE SPECIFIED FOR THAT PROCESS'
text_6 = 'File elaready exist. Please remove the file and try again:'
text_7 = 'Path for process not added'
text_8 = 'Log file not found'
text_10 = 'Could not sent mail using smtplib library'
text_11 = 'Could not sent mail using mailx function'
text_12 = 'Did not found path to file'
text_13 = 'There is no such command for current hostname as '
text_14 = 'Whole application processes are down'
text_15 = 'File for current hostname not found'
text_16 = 'Process NAME field must not be empty'
text_17 = 'Process PATTERN field must not be empty'
text_18 = 'Process NUMBER OF INSTANCES field must not be empty'
text_19 = 'Process LOG UPDATE field must not be empty'
text_20 = 'Did not found any log file maching to pattern.'
text_21 = 'STARTING'
text_22 = 'STOPPING'
text_23 = 'Start script created:'
text_24 = 'End script created:'
text_25 = 'DONE'
text_26 = "Library psutil is not installed. Install psutil library to use it"
text_27 = 'Program closed'
text_29 = 'Script broken by user'
text_30 = 'Index error'
text_31 = 'Unknown error'
text_32 = 'Choose one of below command to gather list of currently working processes:'
text_33 = 'Choosen: '
text_34 = 'Given value is not digit, please give digit.'
text_35 = 'Given value out of range. Please give digit within the range.'
text_36 = 'Choose one of below files to gather list of processes to check:'